name: bd1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.1  
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  provider: ^5.0.0
  path_provider: ^2.0.14


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app.png"
  min_sdk_version: 21
  web:
    generate: true
    image_path: "assets/app.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/app.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image.jpg
    - assets/emptybox.jpeg
    - assets/profile.png
    - assets/img.png
    - assets/qwe.png
    - assets/images/Mpackage1.jpg
    - assets/images/Mpackage2.jpg
    - assets/images/NV200_1.jpg
    - assets/images/NV200_2.jpg
    - assets/images/NV200_3.jpg
    - assets/images/Xle_1.png
    - assets/images/Xle_2.jpg
    - assets/images/Xle_3.jpg
    - assets/images/Xle_4.jpg
    - assets/images/SE_1.jpg
    - assets/images/SE_2.jpg
    - assets/images/SE_3.jpg
    - assets/images/Sante1.jpg
    - assets/images/santa2.jpg
    - assets/images/santa3.jpg
    - assets/images/santa4.jpg
    - assets/basket.png
    - assets/images/selbeg1.png
    - assets/images/camryengine.png
    - assets/images/amortizator1.png
    - assets/images/amortizator.png
    - assets/images/door.png

    
